apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/version: "v1"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-app
      app.kubernetes.io/version: "v1"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-app
        app.kubernetes.io/version: "v1"
    spec:
      containers:
      - name: demo-app
        image: zerofruit/cicd-demo-app:35be44a
        imagePullPolicy: Always
        command: ["java"]
        args: [
          "-jar",
          "/demo-app.jar"
        ]
        ports:
        - containerPort: 8080
